apiVersion: v1
kind: Pod
metadata:
  name: with-nodeaffinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            # - gpu  
            - gpuu          
  containers:
  - name: with-nodeaffinity
    image: nginx
    imagePullPolicy: Always
