apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    appname: pod-1
    purpose: pod-affinity
spec:
  containers:
  - name: pod-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    appname: pod-2
    purpose: pod-affinity
spec:
  affinity:
    podAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
      # - labelSelector:
      #     matchExpressions:
      #     - key: appname
      #       operator: In
      #       values:
      #       - pod-1
      #   topologyKey: "kubernetes.io/hostname"
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: appname
              operator: In
              values:
              - pod-1
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: pod-2
    image: nginx
